// @generated by `cargo run -p xtask -- readme-tests`. Do not edit by hand.
//
// The README's Rust examples, lifted out and compiled. See xtask/src/readme_tests.rs for
// why they are not doctests.
//
// Nothing here is executed. Compiling is the test: an example that no longer type-checks
// is documentation that lies, and that is what this catches.
#![allow(
    unused_variables,
    unused_imports,
    unused_mut,
    unused_macros,
    dead_code,
    unreachable_code,
    // Several fences show how to implement a trait, and every fence is wrapped in a
    // function — so the impl lands inside one. That is the mechanism, not a mistake.
    // Fires on newer toolchains than the pinned one, which is how CI found it.
    non_local_definitions,
    clippy::all
)]

use prkdb::prelude::*;
use prkdb::PrkDb;
pub use prkdb_client::ClientConfig;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use std::time::Duration;

/// The type nearly every example names.
#[derive(Collection, Serialize, Deserialize, Clone, Debug, PartialEq)]
struct User {
    #[id]
    id: String,
    #[index]
    age: u32,
    #[index]
    name: String,
    #[index]
    role: String,
    email: String,
    active: bool,
    created_at: u64,
    updated_at: u64,
    orders: f64,
    salary: f64,
    bio: String,
    dept: String,
    birth_date: u64,
    verified: bool,
    deleted: bool,
}

impl SoftDeletable for User {
    fn is_deleted(&self) -> bool {
        self.deleted
    }
    fn mark_deleted(&mut self) {
        self.deleted = true;
    }
    fn restore(&mut self) {
        self.deleted = false;
    }
}
// Timestamped is deliberately not implemented here: the README shows how to implement it,
// and providing it too makes that example a conflicting-impl error.

#[derive(Collection, Serialize, Deserialize, Clone, Debug, PartialEq)]
struct Order {
    #[id]
    id: String,
    #[index]
    user_id: String,
    total: f64,
}

/// Schema-evolution examples name two versions of the same record.
#[derive(Collection, Serialize, Deserialize, Clone, Debug, PartialEq)]
struct UserV1 {
    #[id]
    id: String,
    name: String,
}

#[derive(Collection, Serialize, Deserialize, Clone, Debug, PartialEq)]
struct UserV2 {
    #[id]
    id: String,
    name: String,
    premium: bool,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
struct UserSummary {
    id: String,
    name: String,
}

pub use prkdb_client::PrkDbClient;
pub use prkdb_types::collection::{
    Hooks, SoftDeletable, Timestamped, Validatable, ValidationError, Versioned,
};

/// Stand-ins for the values the fragments assume are in scope.
///
/// `unimplemented!()` is safe because no function below is ever called — and it keeps the
/// preamble from asserting anything about runtime behaviour it has not checked.
/// Most query examples call `query`, `count`, `sum` — which live on `IndexedStorage`,
/// not on `PrkDb`. The README writes `db` for both without saying which, so the generated
/// tests bind `db` to the one that makes the majority compile and expose the other as
/// `prkdb`. That ambiguity is itself a finding; see the report in docs/.
// The Collection derive emits a per-type `{Struct}QueryExt` trait carrying the generated
// `where_<field>_eq` methods. In a user's own module it is in scope automatically; here
// the fences are functions inside a generated file, so it must be imported explicitly.
#[allow(unused_imports)]
use {OrderQueryExt as _, UserQueryExt as _, UserV1QueryExt as _, UserV2QueryExt as _};

fn a_db() -> prkdb::indexed_storage::IndexedStorage<prkdb::storage::InMemoryAdapter> {
    unimplemented!("examples are compiled, never run")
}
fn a_prkdb() -> PrkDb {
    unimplemented!("examples are compiled, never run")
}
fn a_client() -> PrkDbClient {
    unimplemented!("examples are compiled, never run")
}
fn any_user() -> User {
    unimplemented!("examples are compiled, never run")
}
fn any_storage() -> Arc<prkdb::storage::WalStorageAdapter> {
    unimplemented!("examples are compiled, never run")
}

/// `log` appears in one example; the crate is not a dependency, so this stands in for the
/// macro call rather than adding a dependency for a README fence.
mod log {
    macro_rules! info {
        ($($t:tt)*) => {};
    }
    pub(crate) use info;
}

/// README.md line 98
async fn readme_line_98() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    use prkdb::prelude::*;

    // Basic transaction
    let mut tx = storage.begin_transaction();
    tx.put(b"key1", b"value1")?;
    tx.put(b"key2", b"value2")?;
    tx.commit().await?; // Atomic commit

    // Rollback
    let mut tx = storage.begin_transaction();
    tx.put(b"key1", b"bad_value")?;
    tx.rollback(); // Discard all changes

    // Savepoints (nested transactions)
    let mut tx = storage.begin_transaction();
    tx.put(b"order", b"pending")?;
    tx.savepoint("sp1")?;
    tx.put(b"payment", b"charged")?;
    tx.rollback_to_savepoint("sp1")?; // Undo payment, keep order

    // Conflict detection (Serializable isolation)
    let config = TransactionConfig {
        isolation_level: IsolationLevel::Serializable,
        ..Default::default()
    };
    let mut tx = storage.begin_transaction_with_config(config);
    let _ = tx.get(b"key1").await?; // Tracked for conflicts
                                    // If another transaction modifies key1, commit() returns ConflictDetected
    Ok(())
}

/// README.md line 133
async fn readme_line_133() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    use prkdb::prelude::*;
    use std::time::Duration;

    // Wrap storage with TTL support
    let ttl_storage = TtlStorage::new(storage);

    // Put with 1 hour TTL
    ttl_storage
        .put_with_ttl(b"session:123", b"data", Duration::from_secs(3600))
        .await?;

    // Get returns None if expired
    let value = ttl_storage.get(b"session:123").await?;

    // Check remaining TTL
    let remaining = ttl_storage.ttl(b"session:123").await?;

    // Manually expire
    ttl_storage.expire(b"session:123").await?;

    // Remove TTL (persist forever)
    ttl_storage.persist(b"key").await?;
    Ok(())
}

/// README.md line 160
async fn readme_line_160() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    use tokio_stream::StreamExt;

    // Subscribe to all keys starting with "user:"
    let mut stream = client.watch(b"user:").await?;

    while let Some(event) = stream.next().await {
        match event? {
            // PUT event has key and new value
            e if e.event_type == 0 => println!("Updated: {:?}", e.key),
            // DELETE event has key only
            e => println!("Deleted: {:?}", e.key),
        }
    }
    Ok(())
}

/// README.md line 185
async fn readme_line_185() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    let config = ClientConfig {
        max_retries: 5,
        max_connections_per_node: 8,
        unhealthy_threshold: 3,
        unhealthy_cooldown_secs: 30,
        ..Default::default()
    };
    let client = PrkDbClient::with_config(vec!["http://127.0.0.1:8080".into()], config).await?;
    Ok(())
}

/// README.md line 200
async fn readme_line_200() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    use prkdb::prelude::*;

    #[derive(Collection, Clone, Debug, Serialize, Deserialize)]
    struct User {
        #[key]
        pub id: String,

        #[index]
        pub age: u32,

        #[index(unique)]
        pub email: String,

        // Indexed because the query examples below filter on them.
        #[index]
        pub name: String,
        #[index]
        pub role: String,

        pub active: bool,

        // Read by the closure filter below and by the aggregation examples.
        pub orders: u32,
    }

    // Query by indexed field
    let admins: Vec<User> = db.query_by("role", &"admin").await?;
    let alice: Option<User> = db.query_unique_by("email", &"a@b.com").await?;

    // Range queries
    let adults: Vec<User> = db.query_range("age", &18, &65).await?;
    let al_names: Vec<User> = db.query_prefix("name", "Al").await?;

    // Flexible closure filter (scans all, O(n))
    let vip: Vec<User> = db.filter(|u: &User| u.age > 18 && u.orders > 100).await?;
    Ok(())
}

/// README.md line 240
async fn readme_line_240() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    db.insert_batch(&[user1.clone(), user2.clone(), user3])
        .await?; // Returns count
    db.delete_batch(&[user1, user2]).await?;
    Ok(())
}

/// README.md line 247
async fn readme_line_247() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    let page1: Vec<User> = db.paginate(10, 0).await?; // limit=10, offset=0
    let page2: Vec<User> = db.paginate(10, 10).await?; // Next page
    let filtered: Vec<User> = db.filter_paginated(|u: &User| u.age > 18, 5, 0).await?;
    Ok(())
}

/// README.md line 255
async fn readme_line_255() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    let count = db.count::<User>().await?;
    let total: f64 = db.sum(|u: &User| u.orders as f64).await?;
    let avg = db.avg(|u: &User| u.age as f64).await?;
    let min = db.min(|u: &User| u.age).await?;
    let max = db.max(|u: &User| u.age).await?;
    let adults = db.count_where(|u: &User| u.age >= 18).await?;
    Ok(())
}

/// README.md line 266
async fn readme_line_266() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Works with any StorageAdapter
    let indexed = IndexedStorage::new(any_storage_adapter);
    Ok(())
}

/// README.md line 273
async fn readme_line_273() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Subscribe to changes
    let mut rx = db.watch();
    tokio::spawn(async move {
        while let Ok(event) = rx.recv().await {
            match event {
                ChangeEvent::Inserted { collection, id, .. } => println!("New!"),
                ChangeEvent::Deleted { collection, id } => println!("Gone!"),
            }
        }
    });
    Ok(())
}

/// README.md line 310
async fn readme_line_310() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Create compound index at runtime
    db.create_compound_index("role_age", |u: &User| {
        vec![u.role.clone(), u.age.to_string()]
    })
    .await?;

    // Query by multiple fields
    let admins_30 = db
        .query_compound::<User>("role_age", vec!["Admin".into(), "30".into()])
        .await?;
    Ok(())
}

/// README.md line 324
async fn readme_line_324() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Load indexes from disk on startup (or create fresh if not found)
    // `mut` because start_auto_sync/stop_auto_sync below take &mut self.
    let mut db = IndexedStorage::load_from(storage, "./data/indexes.db").await?;

    // Save before shutdown or periodically
    db.save_indexes("./data/indexes.db").await?;

    // Get index stats
    let stats = db.index_stats().await; // BTreeMap<collection, count>

    // Auto-sync in background (recommended!)
    db.start_auto_sync(Duration::from_secs(30)).await;
    // Indexes saved automatically every 30 seconds

    // On shutdown
    db.stop_auto_sync();
    Ok(())
}

/// README.md line 347
async fn readme_line_347() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Fluent query building with type-safe field methods
    let users = db
        .query::<User>()
        .where_role_eq("admin") // Generated method
        .where_age_gt(18) // Generated method
        .filter(|u| u.verified) // Generic closure
        .order_by(|u| u.created_at)
        .take(10)
        .collect()
        .await?;

    // Projection to different type
    let summaries = db
        .query::<User>()
        .where_role_eq("admin")
        .select(|u| UserSummary {
            id: u.id,
            name: u.name.clone(),
        })
        .collect()
        .await?;
    Ok(())
}

/// README.md line 374
async fn readme_line_374() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Get unique values
    let roles = db.query::<User>().distinct(|u| u.role.clone()).await?;

    // Group by key
    let by_role = db.query::<User>().group_by(|u| u.role.clone()).await?;

    // Sum/Count by group
    let salaries = db
        .query::<User>()
        .sum_by(|u| u.dept.clone(), |u| u.salary)
        .await?;
    let counts = db.query::<User>().count_by(|u| u.role.clone()).await?;
    Ok(())
}

/// README.md line 389
async fn readme_line_389() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Create text index
    db.create_text_index::<User, _>("bio", |u| &u.bio).await?;

    // Search with ranked results
    let users = db.search::<User>("bio", "rust async developer").await?;
    // Results ranked by number of matching tokens
    Ok(())
}

/// README.md line 417
async fn readme_line_417() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Start a transaction
    let mut tx = db.transaction();

    // Buffer operations
    tx.insert(&user1)?;
    tx.insert(&user2)?;
    tx.delete(&old_user)?;

    // Commit all atomically
    tx.commit().await?;

    // OR: Rollback to discard all
    // tx.rollback();
    Ok(())
}

/// README.md line 435
async fn readme_line_435() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Versioned collections support migration
    impl Versioned for UserV2 {
        const VERSION: u32 = 2;
        type PreviousVersion = UserV1;

        fn migrate(old: UserV1) -> Self {
            Self {
                id: old.id,
                name: old.name,
                premium: false,
            }
        }
    }
    Ok(())
}

/// README.md line 449
async fn readme_line_449() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Define validation rules
    impl Validatable for User {
        fn validate(&self) -> Result<(), Vec<ValidationError>> {
            let mut errors = Vec::new();
            if self.name.is_empty() {
                errors.push(ValidationError::new("name", "cannot be empty"));
            }
            if !self.email.contains('@') {
                errors.push(ValidationError::new("email", "invalid format"));
            }
            if errors.is_empty() {
                Ok(())
            } else {
                Err(errors)
            }
        }
    }

    // Auto-validate on insert
    db.insert_validated(&user).await?;
    Ok(())
}

/// README.md line 470
async fn readme_line_470() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // First page
    let (users, next_cursor) = db
        .query::<User>()
        .order_by(|u| u.id.clone())
        .paginate(10, None)
        .await?;

    // Next page
    if let Some(cursor) = next_cursor {
        let (more, _) = db
            .query::<User>()
            .order_by(|u| u.id.clone())
            .paginate(10, Some(cursor))
            .await?;
    }

    // Or use after() directly
    let page2 = db
        .query::<User>()
        .after(&last_id)
        .take(10)
        .collect()
        .await?;
    Ok(())
}

/// README.md line 492
async fn readme_line_492() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    use prkdb::cache::LruCache;

    let cache = LruCache::<String, User>::new(1000);
    cache.put(user_id.clone(), user);

    if let Some(user) = cache.get(&user_id) {
        // Cache hit
    }

    let stats = cache.stats();
    println!("{:.1}% utilized", stats.utilization());
    Ok(())
}

/// README.md line 508
async fn readme_line_508() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // User has many Orders (eager load, avoids N+1)
    let users_with_orders = db
        .query::<User>()
        .collect_with::<Order, _, _>(
            |user| user.id.clone(),        // parent key
            |order| order.user_id.clone(), // foreign key
        )
        .await?; // Vec<(User, Vec<Order>)>

    // Order belongs to User
    let orders_with_user = db
        .query::<Order>()
        .collect_with_one::<User, _>(|order| order.user_id.clone())
        .await?; // Vec<(Order, Option<User>)>
    Ok(())
}

/// README.md line 524
async fn readme_line_524() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Upsert: Insert or update if exists
    db.upsert(&user).await?; // Returns true if updated, false if inserted

    // Update: Modify existing record with closure
    db.update::<User, _>(&user_id, |u| {
        u.name = "New Name".to_string();
        u.age += 1;
    })
    .await?;

    // Check existence
    if db.exists::<User>(&user_id).await? {
        println!("user {user_id} is present");
    }
    Ok(())
}

/// README.md line 542
async fn readme_line_542() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Mark as deleted (keeps data)
    db.soft_delete::<User>(&user_id).await?;

    // Query only active records
    let active = db.query_active::<User>().await?;

    // Restore a soft-deleted record
    db.restore::<User>(&user_id).await?;
    Ok(())
}

/// README.md line 555
async fn readme_line_555() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    impl Timestamped for User {
        fn created_at(&self) -> u64 {
            self.created_at
        }
        fn updated_at(&self) -> u64 {
            self.updated_at
        }
        fn set_created_at(&mut self, ts: u64) {
            self.created_at = ts;
        }
        fn set_updated_at(&mut self, ts: u64) {
            self.updated_at = ts;
        }
    }

    // Auto-set timestamps on insert
    db.insert_timestamped(&mut user).await?;

    // Auto-update on upsert
    db.upsert_timestamped(&mut user).await?;
    Ok(())
}

/// README.md line 572
async fn readme_line_572() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Add computed fields to query results
    let users_with_age = db
        .query::<User>()
        .with_computed(|user| (now - user.birth_date) / 86400)
        .await?; // Vec<WithComputed<User, u64>>

    for item in users_with_age {
        println!("{}: {} days old", item.record.name, item.computed);
    }
    Ok(())
}

/// README.md line 585
async fn readme_line_585() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Get stats for a collection
    let stats = db.collection_stats::<User>().await;
    println!("User Index: {}", stats);
    // "Fields: 3 | Values: 100 | Entries: 150 | Compound: 0 | Text: 1"

    // Get stats for all collections
    let all_stats = db.all_collection_stats().await;
    Ok(())
}

/// README.md line 597
async fn readme_line_597() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    impl Hooks for User {
        fn before_insert(&mut self) -> Result<(), String> {
            self.name = self.name.trim().to_string(); // Normalize
            Ok(())
        }
        fn after_insert(&self) {
            println!("User {} created", self.id);
        }
    }

    // Auto-run hooks on insert/delete
    db.insert_with_hooks(&mut user).await?;
    db.delete_with_hooks(&user).await?;
    Ok(())
}

/// README.md line 615
async fn readme_line_615() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    use prkdb::rate_limit::RateLimiter;

    let limiter = RateLimiter::per_second(100); // 100 ops/sec

    // Wait for permission before operation
    limiter.acquire().await;
    db.insert(&record).await?;

    // Or try without waiting
    if limiter.try_acquire().await {
        db.insert(&record).await?;
    }
    Ok(())
}

/// README.md line 632
async fn readme_line_632() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Create snapshot for backup
    let snapshot: Vec<User> = db.snapshot::<User>().await?;

    // Clone to another storage
    db.clone_to::<User>(&backup_db).await?;
    Ok(())
}

/// README.md line 642
async fn readme_line_642() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Find first matching record
    let admin = db
        .find_one::<User, _>(|u| u.role.clone() == "admin")
        .await?;

    // Find all matching records
    let admins = db
        .find_all::<User, _>(|u| u.role.clone() == "admin")
        .await?;
    Ok(())
}

/// README.md line 652
async fn readme_line_652() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Delete all matching records
    let deleted = db.delete_where::<User, _>(|u| !u.active).await?;

    // Update all matching records
    let updated = db
        .update_where::<User, _, _>(|u| !u.verified, |u| u.verified = true)
        .await?;
    Ok(())
}

/// README.md line 665
async fn readme_line_665() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Find min/max by field
    let youngest = db.query::<User>().min_by(|u| u.age).await?;
    let oldest = db.query::<User>().max_by(|u| u.age).await?;

    // Calculate average
    let avg_age = db.query::<User>().avg_by(|u| u.age as f64).await?;

    // Boolean checks
    let has_admin = db
        .query::<User>()
        .any(|u| u.role.clone() == "admin")
        .await?;
    let all_active = db.query::<User>().all(|u| u.active).await?;
    Ok(())
}

/// README.md line 680
async fn readme_line_680() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Extract single field (like SQL SELECT column)
    let names: Vec<String> = db.query::<User>().pluck(|u| u.name.clone()).await?;

    // Partition into matching/non-matching
    let (active, inactive) = db.query::<User>().partition(|u| u.active).await?;

    // Custom fold/reduce
    let total_salary = db
        .query::<User>()
        .fold(0.0, |acc, u| acc + u.salary)
        .await?;

    // Random sample
    let sample = db.query::<User>().sample(5).await?; // 5 random users

    // Get last record
    let last = db.query::<User>().last().await?;

    // Take/skip while condition
    let early = db.query::<User>().take_while(|u| u.age < 100).await?;
    Ok(())
}

/// README.md line 702
async fn readme_line_702() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    // Process in chunks/batches
    let chunks = db.query::<User>().chunks(100).await?; // Vec<Vec<User>>

    // Add index to records
    let indexed = db.query::<User>().enumerate().await?; // Vec<(usize, User)>

    // Remove consecutive duplicates
    let deduped = db
        .query::<User>()
        .order_by(|u| u.role.clone())
        .dedup_by_key(|u| u.role.clone())
        .await?;

    // Join with another collection
    let joined = db
        .query::<Order>()
        .join_with(&users, |o| o.user_id.clone(), |u| u.id.clone())
        .await?; // Vec<(Order, Option<User>)>
    Ok(())
}

/// README.md line 778
async fn readme_line_778() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    use prkdb::raft::rpc::ReadMode;

    // These three are methods on `PrkDb`, not on `IndexedStorage`.
    let db = PrkDb::builder().build()?;

    // Linearizable (default) - Always reads from leader
    let value = db.get(&key).await?;

    // Stale read - Fast local read (may be stale)
    let value = db.get_local(&key).await?;

    // Follower read - Linearizable from any node
    let value = db.get_follower_read(&key).await?;
    Ok(())
}

/// README.md line 796
async fn readme_line_796() -> Result<(), Box<dyn std::error::Error>> {
    let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    use prkdb::raft::{ConsistentHashRing, RangePartitioner};

    // Consistent hashing (default) - Minimal data movement on rebalance
    let ring = ConsistentHashRing::new(3, 150); // 3 partitions, 150 virtual nodes
    let partition: u64 = ring.get_partition_for_key(&key);

    // Which node currently owns that key
    let owner = ring.get_node(&key);

    // Range partitioning - For ordered access patterns
    let partitioner = RangePartitioner::new(3);
    let partition: u64 = partitioner.get_partition_for_key(&key);

    // Split hotspots
    let new_partition = partitioner.split_partition(b"middle_key".to_vec());
    Ok(())
}

// 36 example(s) compiled, 1 skipped.
// skipped README.md line 39: complete program: has its own fn main
