// @generated by `cargo run -p xtask -- readme-tests`. Do not edit by hand.
//
// The README's Rust examples, lifted out and compiled. See xtask/src/readme_tests.rs for
// why they are not doctests.
//
// Nothing here is executed. Compiling is the test: an example that no longer type-checks
// is documentation that lies, and that is what this catches.
#![allow(
    unused_variables,
    unused_imports,
    unused_mut,
    unused_macros,
    dead_code,
    unreachable_code,
    clippy::all
)]

use prkdb::prelude::*;
use prkdb::PrkDb;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use std::time::Duration;
pub use prkdb_client::ClientConfig;

/// The type nearly every example names.
#[derive(Collection, Serialize, Deserialize, Clone, Debug, PartialEq)]
struct User {
    #[id]
    id: String,
    #[index]
    age: u32,
    #[index]
    name: String,
    #[index]
    role: String,
    email: String,
    active: bool,
    created_at: u64,
    updated_at: u64,
    orders: f64,
    salary: f64,
    bio: String,
    dept: String,
    birth_date: u64,
    verified: bool,
    deleted: bool,
}

impl SoftDeletable for User {
    fn is_deleted(&self) -> bool { self.deleted }
    fn mark_deleted(&mut self) { self.deleted = true; }
    fn restore(&mut self) { self.deleted = false; }
}
impl Timestamped for User {
    fn created_at(&self) -> u64 { self.created_at }
    fn updated_at(&self) -> u64 { self.updated_at }
    fn set_created_at(&mut self, t: u64) { self.created_at = t; }
    fn set_updated_at(&mut self, t: u64) { self.updated_at = t; }
}

#[derive(Collection, Serialize, Deserialize, Clone, Debug, PartialEq)]
struct Order {
    #[id]
    id: String,
    #[index]
    user_id: String,
    total: f64,
}

/// Schema-evolution examples name two versions of the same record.
#[derive(Collection, Serialize, Deserialize, Clone, Debug, PartialEq)]
struct UserV1 {
    #[id]
    id: String,
    name: String,
}

#[derive(Collection, Serialize, Deserialize, Clone, Debug, PartialEq)]
struct UserV2 {
    #[id]
    id: String,
    name: String,
    email: String,
    premium: bool,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
struct UserSummary {
    id: String,
    name: String,
}

pub use prkdb_client::PrkDbClient;
pub use prkdb_types::collection::{
    Hooks, SoftDeletable, Timestamped, Validatable, ValidationError, Versioned,
};

/// Stand-ins for the values the fragments assume are in scope.
///
/// `unimplemented!()` is safe because no function below is ever called — and it keeps the
/// preamble from asserting anything about runtime behaviour it has not checked.
/// Most query examples call `query`, `count`, `sum` — which live on `IndexedStorage`,
/// not on `PrkDb`. The README writes `db` for both without saying which, so the generated
/// tests bind `db` to the one that makes the majority compile and expose the other as
/// `prkdb`. That ambiguity is itself a finding; see the report in docs/.
#[allow(unused_imports)]
use {UserQueryExt as _, OrderQueryExt as _, UserV1QueryExt as _, UserV2QueryExt as _};

fn a_db() -> prkdb::indexed_storage::IndexedStorage<prkdb::storage::InMemoryAdapter> {
    unimplemented!("examples are compiled, never run")
}
fn a_prkdb() -> PrkDb {
    unimplemented!("examples are compiled, never run")
}
fn a_client() -> PrkDbClient {
    unimplemented!("examples are compiled, never run")
}
fn any_user() -> User {
    unimplemented!("examples are compiled, never run")
}
fn any_storage() -> Arc<prkdb::storage::WalStorageAdapter> {
    unimplemented!("examples are compiled, never run")
}

/// `log` appears in one example; the crate is not a dependency, so this stands in for the
/// macro call rather than adding a dependency for a README fence.
mod log {
    macro_rules! info {
        ($($t:tt)*) => {};
    }
    pub(crate) use info;
}

/// README.md line 98
async fn readme_line_98() -> Result<(), Box<dyn std::error::Error>> {
let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    use prkdb::prelude::*;

    // Basic transaction
    let mut tx = storage.begin_transaction();
    tx.put(b"key1", b"value1")?;
    tx.put(b"key2", b"value2")?;
    tx.commit().await?;  // Atomic commit

    // Rollback
    let mut tx = storage.begin_transaction();
    tx.put(b"key1", b"bad_value")?;
    tx.rollback();  // Discard all changes

    // Savepoints (nested transactions)
    let mut tx = storage.begin_transaction();
    tx.put(b"order", b"pending")?;
    tx.savepoint("sp1")?;
    tx.put(b"payment", b"charged")?;
    tx.rollback_to_savepoint("sp1")?;  // Undo payment, keep order

    // Conflict detection (Serializable isolation)
    let config = TransactionConfig {
        isolation_level: IsolationLevel::Serializable,
        ..Default::default()
    };
    let mut tx = storage.begin_transaction_with_config(config);
    let _ = tx.get(b"key1").await?;  // Tracked for conflicts
    // If another transaction modifies key1, commit() returns ConflictDetected
    Ok(())
}

/// README.md line 133
async fn readme_line_133() -> Result<(), Box<dyn std::error::Error>> {
let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    use prkdb::prelude::*;
    use std::time::Duration;

    // Wrap storage with TTL support
    let ttl_storage = TtlStorage::new(storage);

    // Put with 1 hour TTL
    ttl_storage.put_with_ttl(b"session:123", b"data", Duration::from_secs(3600)).await?;

    // Get returns None if expired
    let value = ttl_storage.get(b"session:123").await?;

    // Check remaining TTL
    let remaining = ttl_storage.ttl(b"session:123").await?;

    // Manually expire
    ttl_storage.expire(b"session:123").await?;

    // Remove TTL (persist forever)
    ttl_storage.persist(b"key").await?;
    Ok(())
}

/// README.md line 160
async fn readme_line_160() -> Result<(), Box<dyn std::error::Error>> {
let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    use tokio_stream::StreamExt;

    // Subscribe to all keys starting with "user:"
    let mut stream = client.watch(b"user:").await?;

    while let Some(event) = stream.next().await {
        match event? {
            // PUT event has key and new value
            e if e.event_type == 0 => println!("Updated: {:?}", e.key),
            // DELETE event has key only
            e => println!("Deleted: {:?}", e.key),
        }
    }
    Ok(())
}

/// README.md line 185
async fn readme_line_185() -> Result<(), Box<dyn std::error::Error>> {
let mut db = a_db();
    let client = a_client();
    let mut storage = any_storage();
    let any_storage_adapter = any_storage();
    let backup_db = a_db();
    let prkdb = a_prkdb();
    let mut user = any_user();
    let mut user1 = any_user();
    let mut user2 = any_user();
    let mut user3 = any_user();
    let mut old_user = any_user();
    let mut record = any_user();
    let users: Vec<User> = Vec::new();
    let user_id = String::new();
    let last_id = String::new();
    let key = b"users:1".to_vec();
    let now: u64 = 0;
    let config = ClientConfig {
        max_retries: 5,
        max_connections_per_node: 8,
        unhealthy_threshold: 3,
        unhealthy_cooldown_secs: 30,
        ..Default::default()
    };
    let client = PrkDbClient::with_config(vec!["http://127.0.0.1:8080".into()], config).await?;
    Ok(())
}

// 4 example(s) compiled, 33 skipped.
// skipped README.md line 39: complete program: has its own fn main
// skipped README.md line 200: its User derives no Debug, but later examples print it
// skipped README.md line 229: uses an `orders` field the User at line 200 does not declare
// skipped README.md line 236: aggregate closure return type is not inferable as written
// skipped README.md line 244: same
// skipped README.md line 255: same
// skipped README.md line 262: same
// skipped README.md line 299: same
// skipped README.md line 313: same
// skipped README.md line 335: uses generated query methods without importing UserQueryExt
// skipped README.md line 362: same
// skipped README.md line 377: same
// skipped README.md line 405: same
// skipped README.md line 423: same
// skipped README.md line 437: same
// skipped README.md line 458: same
// skipped README.md line 480: annotated result type does not match what the call returns
// skipped README.md line 496: same
// skipped README.md line 512: contains literal `...` placeholders; illustrative, not runnable
// skipped README.md line 528: same type mismatch
// skipped README.md line 541: re-implements Timestamped for User, which the preamble already provides
// skipped README.md line 558: same type mismatch
// skipped README.md line 571: same
// skipped README.md line 583: same
// skipped README.md line 601: same
// skipped README.md line 618: same
// skipped README.md line 628: same
// skipped README.md line 638: same
// skipped README.md line 651: same
// skipped README.md line 666: compares a String id against an integer
// skipped README.md line 688: same
// skipped README.md line 764: annotated result type does not match what the call returns
// skipped README.md line 779: same
