#!/usr/bin/env bash
# Captures §6.1 metrics for the current tree into $1 (TOML). Wall-clock numbers from the
# maintainer machine; record machine details so later comparisons are like-for-like.
#
# This baseline is a REFERENCE, not a target: single-node write numbers are inflated by
# STO-02 (writes acked before fsync). It measures each fix's cost, phase to phase.
#
# Bench selection follows spec §6.1's rows, one representative bench per row rather than
# every file that touches storage:
#   - put / batch put / point get           -> storage_bench, batch_bench (crates/prkdb)
#   - point get / index query                -> query_bench (crates/prkdb)
#   - consumer poll throughput                -> consumer_bench (crates/prkdb)
#   - end-to-end put -> WAL -> consumer.poll  -> e2e_throughput_bench (TST-04; crates/prkdb)
#   - recovery time for a large WAL           -> recovery_bench (new; crates/prkdb)
#   - 3-node write throughput                 -> cluster_write_bench (new; crates/prkdb)
#
# `iai_hot_paths` (Task 1.13) is intentionally excluded: it reports Valgrind instruction
# counts for the deterministic CI gate, not Criterion ns/iter, and does not run on macOS
# at all (see .github/workflows/perf-gate.yml).
set -euo pipefail
cd "$(dirname "$0")/.."
out=${1:?usage: capture_baseline.sh <out.toml>}

# Criterion's own default warm-up (3s) and measurement (5s) windows, times the ~30
# benchmark functions across these files, would run well past the ~5 minute measurement
# budget this task is held to. Shortened here; per-benchmark deltas are still visible in
# the bencher-format log, just noisier than a full default run.
: "${WARM_UP_TIME:=1}"
: "${MEASUREMENT_TIME:=2}"

# Write to a temp file and mv into place at the end, so a run that fails partway (or is
# interrupted) never leaves a half-written baseline sitting at $out looking legitimate.
tmp_out="$out.tmp"
log_dir="target/capture_baseline_logs"
mkdir -p "$log_dir"
rm -f "$tmp_out"

{
  echo "# Generated by scripts/capture_baseline.sh on $(date -u +%F)"
  echo "commit = \"$(git rev-parse --short HEAD)\""
  echo "machine = \"$(uname -srm) / $(sysctl -n machdep.cpu.brand_string 2>/dev/null || grep -m1 'model name' /proc/cpuinfo | cut -d: -f2 | sed 's/^ *//')\""
} > "$tmp_out"

for bench in e2e_throughput_bench storage_bench batch_bench query_bench consumer_bench recovery_bench cluster_write_bench; do
  # --output-format bencher prints one line per benchmark
  # ("test <name> ... bench: <ns> ns/iter (+/- <ns>)"), which survives long names that
  # Criterion's default output wraps onto two lines.
  #
  # stderr goes to a log file under target/ (not /tmp, which is shared and can be
  # cleaned out from under a long-running capture, and not /dev/null, which throws
  # away the one thing you need when a bench panics) so it survives for inspection and
  # is printed here on failure.
  log_file="$log_dir/$bench.stderr.log"
  bench_log="$log_dir/$bench.stdout.log"
  if ! cargo bench -p prkdb --bench "$bench" -- \
      --warm-up-time "$WARM_UP_TIME" --measurement-time "$MEASUREMENT_TIME" \
      --output-format bencher > "$bench_log" 2> "$log_file"; then
    echo "capture_baseline.sh: $bench failed; stderr from $log_file:" >&2
    cat "$log_file" >&2
    exit 1
  fi

  echo "" >> "$tmp_out"
  echo "[$bench]" >> "$tmp_out"
  parsed=$(sed -nE 's/^test (.+) \.\.\. bench: +([0-9,]+) ns\/iter.*/"\1" = \2/p' "$bench_log" | tr -d ',')
  if [ -z "$parsed" ]; then
    echo "capture_baseline.sh: $bench produced zero parsed lines from $bench_log; stderr was:" >&2
    cat "$log_file" >&2
    exit 1
  fi
  echo "$parsed" >> "$tmp_out"
done

mv "$tmp_out" "$out"
echo "wrote $out"
