//! Renders docs/status/remediation.md. Security findings are hidden until fixed (§5.1).

use super::model::{Ledger, Status};
use std::fmt::Write;

pub fn render(ledger: &Ledger) -> String {
    let mut out = String::new();
    writeln!(out, "# Remediation status\n").unwrap();
    writeln!(
        out,
        "<!-- Generated by `cargo xtask remediation render`. Do not edit by hand. -->\n"
    )
    .unwrap();
    writeln!(out, "Tracks the root-cause remediation program. A finding is **verified** only when its regression tests passed in public CI (and, for storage, keys, events, transactions, TTL and Raft, the crash/restart harness).\n").unwrap();

    writeln!(
        out,
        "## Phases\n\n| Phase | Title | Status | Findings verified |\n|---|---|---|---|"
    )
    .unwrap();
    for p in &ledger.phase {
        let all: Vec<_> = ledger.finding.iter().filter(|f| f.phase == p.id).collect();
        let done = all
            .iter()
            .filter(|f| {
                matches!(
                    f.status,
                    Status::Verified | Status::WontFix | Status::Duplicate
                )
            })
            .count();
        writeln!(
            out,
            "| {} | {} | {:?} | {}/{} |",
            p.id,
            p.title,
            p.status,
            done,
            all.len()
        )
        .unwrap();
    }

    let mut visible: Vec<_> = ledger
        .finding
        .iter()
        .filter(|f| !f.security || matches!(f.status, Status::Fixed | Status::Verified))
        .collect();
    visible.sort_by(|a, b| {
        (is_closed(a.status), a.severity, &a.id).cmp(&(is_closed(b.status), b.severity, &b.id))
    });

    writeln!(
        out,
        "\n## Findings\n\n| ID | Severity | Phase | Status | Title |\n|---|---|---|---|---|"
    )
    .unwrap();
    for f in visible {
        writeln!(
            out,
            "| {} | {:?} | {} | {:?} | {} |",
            f.id,
            f.severity,
            f.phase,
            f.status,
            f.title.replace('|', "\\|")
        )
        .unwrap();
    }
    out
}

fn is_closed(s: Status) -> bool {
    matches!(s, Status::Verified | Status::WontFix | Status::Duplicate)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hides_unfixed_security_findings() {
        let l = Ledger::parse(
            "[[finding]]\nid = \"SCH-01\"\ntitle = \"secret\"\narea = \"schema\"\nseverity = \"high\"\nphase = 0\nstatus = \"open\"\nsecurity = true\n",
        )
        .unwrap();
        assert!(!render(&l).contains("SCH-01"));
    }

    #[test]
    fn open_criticals_sort_first() {
        let l = Ledger::parse(concat!(
            "[[finding]]\nid = \"DOC-06\"\ntitle = \"low\"\narea = \"docs\"\nseverity = \"low\"\nphase = 0\nstatus = \"open\"\n",
            "[[finding]]\nid = \"STO-01\"\ntitle = \"crit\"\narea = \"storage\"\nseverity = \"critical\"\nphase = 2\nstatus = \"open\"\n",
        ))
        .unwrap();
        let text = render(&l);
        assert!(text.find("STO-01").unwrap() < text.find("DOC-06").unwrap());
    }
}
